pipeline {
    agent any

    stages {
        stage('Докачка библиотек') {
            steps {
                echo 'Докачивание модулей'
                sh './updateLibs'
            }
        }
        stage('Тестирование') {
            steps {
                echo 'Выполняем команды для тестирования'
                sh './runTests'
            }
        }
        stage('Сборка') {
            steps {
                echo 'Выполняем команды для сборки'
                sh './runBuild'
            }
        }
    }
}

