pipeline {
    agent any

    stages {
        stage('Докачка библиотек') {
            steps {
                sh 'cd client'
                sh 'npm i'
            }
        }
        stage('Тестирование') {
            steps {
                echo 'Выполняем команды для тестирования'
                sh 'npm test'
            }
        }
        stage('Сборка') {
            steps {
                echo 'Выполняем команды для сборки'
                sh 'npm build'
            }
        }
    }
}

