export const SET_PET_TYPE: "SET_PET_TYPE" = "SET_PET_TYPE";
export const SET_PET_GENDER: "SET_PET_GENDER" = "SET_PET_GENDER";
export const SET_PET_CAN_SWIM: "SET_PET_CAN_SWIM" = "SET_PET_CAN_SWIM";
export const SET_PET_AGE: "SET_PET_AGE" = "SET_PET_AGE";
export const SET_PET_CAN_REPRODUCE: "SET_PET_CAN_REPRODUCE" =
    "SET_PET_CAN_REPRODUCE";
export const SET_PET_SHOP_ID: "SET_PET_SHOP_ID" = "SET_PET_SHOP_ID";
export const SET_PET_PRICE: "SET_PET_PRICE" = "SET_PET_PRICE";
export const SET_PET_NAME: "SET_PET_NAME" = "SET_PET_NAME";
export const SET_PET_BREED: "SET_PET_BREED" = "SET_PET_BREED";
export const SET_PET_AVAILABILITY: "SET_PET_AVAILABILITY" =
    "SET_PET_AVAILABILITY";
export const SET_PET_COLOR: "SET_PET_COLOR" = "SET_PET_COLOR";

export const SET_PET: "SET_PET" = "SET_PET";
export const SET_PET_CREATOR_MODE: "SET_PET_CREATOR_MODE" =
    "SET_PET_CREATOR_MODE";
